name: SHEET ➔ Process Google Sheet Update

# 1. This is the trigger section
on:
  # This listens for the "repository_dispatch" event sent from your Apps Script
  repository_dispatch:
    # This MUST match the 'GITHUB_EVENT_TYPE' variable in your Apps Script
    types: [ google_sheet_updated ]

  # This adds a "Run workflow" button to the Actions tab in GitHub
  # It's extremely useful for testing your script without
  # editing the Google Sheet and waiting 15 minutes.
  workflow_dispatch:


jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Get your repository's code
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Set up a Python environment
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    # Step 3: Install uv (the fast, modern way)
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    # Step 4: Install your project's dependencies using uv
    # uv will find your requirements.txt or pyproject.toml
    # and install dependencies into a virtual environment.
    - name: Install dependencies with uv
      run: uv sync

    # Step 5: Run your Python script
    - name: Run main Python script
      env:
        # This securely passes the data from the Apps Script payload
        # into your script as environment variables.
        GOOGLE_SHEET_ID: ${{ github.event.client_payload.spreadsheet_id }}
        GOOGLE_TAB_ID: ${{ github.event.client_payload.spreadsheet_tab_id }}
        LOGGER_LEVEL: DEBUG
      run: |
        # Activate the virtual environment created by uv
        uv run co2-synthesis
